/*
* Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
*/

/*
* API: https://openweathermap.org/forecast5#data
*/
import 'package:demo/const/env.dart';

class WeatherCallDaysCityCoord {
/*
{
  "lat": 51.5085,
  "lon": -0.1257
} 
*/

  double? lat;
  double? lon;

  WeatherCallDaysCityCoord({
    this.lat,
    this.lon,
  });
  WeatherCallDaysCityCoord.fromJson(Map<String, dynamic> json) {
    lat = json["lat"]?.toDouble();
    lon = json["lon"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["lat"] = lat;
    data["lon"] = lon;
    return data;
  }
}

class WeatherCallDaysCity {
/*
{
  "id": 2643743,
  "name": "London",
  "coord": {
    "lat": 51.5085,
    "lon": -0.1257
  },
  "country": "GB",
  "population": 1000000,
  "timezone": 3600,
  "sunrise": 1627878351,
  "sunset": 1627933654
} 
*/

  int? id;
  String? name;
  WeatherCallDaysCityCoord? coord;
  String? country;
  int? population;
  int? timezone;
  int? sunrise;
  int? sunset;

  WeatherCallDaysCity({
    this.id,
    this.name,
    this.coord,
    this.country,
    this.population,
    this.timezone,
    this.sunrise,
    this.sunset,
  });
  WeatherCallDaysCity.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    coord = (json["coord"] != null)
        ? WeatherCallDaysCityCoord.fromJson(json["coord"])
        : null;
    country = json["country"]?.toString();
    population = json["population"]?.toInt();
    timezone = json["timezone"]?.toInt();
    sunrise = json["sunrise"]?.toInt();
    sunset = json["sunset"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    if (coord != null) {
      data["coord"] = coord!.toJson();
    }
    data["country"] = country;
    data["population"] = population;
    data["timezone"] = timezone;
    data["sunrise"] = sunrise;
    data["sunset"] = sunset;
    return data;
  }
}

class WeatherCallDaysListSys {
/*
{
  "pod": "d"
} 
*/

  String? pod;

  WeatherCallDaysListSys({
    this.pod,
  });
  WeatherCallDaysListSys.fromJson(Map<String, dynamic> json) {
    pod = json["pod"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["pod"] = pod;
    return data;
  }
}

class WeatherCallDaysListWind {
/*
{
  "speed": 1.37,
  "deg": 59,
  "gust": 1.64
} 
*/

  double? speed;
  int? deg;
  double? gust;

  WeatherCallDaysListWind({
    this.speed,
    this.deg,
    this.gust,
  });
  WeatherCallDaysListWind.fromJson(Map<String, dynamic> json) {
    speed = json["speed"]?.toDouble();
    deg = json["deg"]?.toInt();
    gust = json["gust"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["speed"] = speed;
    data["deg"] = deg;
    data["gust"] = gust;
    return data;
  }
}

class WeatherCallDaysListClouds {
/*
{
  "all": 14
} 
*/

  int? all;

  WeatherCallDaysListClouds({
    this.all,
  });
  WeatherCallDaysListClouds.fromJson(Map<String, dynamic> json) {
    all = json["all"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["all"] = all;
    return data;
  }
}

class WeatherCallDaysListWeather {
/*
{
  "id": 801,
  "main": "Clouds",
  "description": "few clouds",
  "icon": "02d"
} 
*/

  int? id;
  String? main;
  String? description;
  String? icon;

  WeatherCallDaysListWeather({
    this.id,
    this.main,
    this.description,
    this.icon,
  });
  WeatherCallDaysListWeather.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    main = json["main"]?.toString();
    description = json["description"]?.toString();
    icon = json["icon"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["main"] = main;
    data["description"] = description;
    data["icon"] = icon;
    return data;
  }

  String getIconUrl() {
    return Env.WEATHER_IMAGES_URL + icon! + '.png';
  }
}

class WeatherCallDaysListMain {
/*
{
  "temp": 18.55,
  "feels_like": 17.9,
  "temp_min": 18.55,
  "temp_max": 20.84,
  "pressure": 1016,
  "sea_level": 1016,
  "grnd_level": 1012,
  "humidity": 55,
  "temp_kf": -2.29
} 
*/

  double? temp;
  double? feelsLike;
  double? tempMin;
  double? tempMax;
  int? pressure;
  int? seaLevel;
  int? grndLevel;
  int? humidity;
  double? tempKf;

  WeatherCallDaysListMain({
    this.temp,
    this.feelsLike,
    this.tempMin,
    this.tempMax,
    this.pressure,
    this.seaLevel,
    this.grndLevel,
    this.humidity,
    this.tempKf,
  });
  WeatherCallDaysListMain.fromJson(Map<String, dynamic> json) {
    temp = json["temp"]?.toDouble();
    feelsLike = json["feels_like"]?.toDouble();
    tempMin = json["temp_min"]?.toDouble();
    tempMax = json["temp_max"]?.toDouble();
    pressure = json["pressure"]?.toInt();
    seaLevel = json["sea_level"]?.toInt();
    grndLevel = json["grnd_level"]?.toInt();
    humidity = json["humidity"]?.toInt();
    tempKf = json["temp_kf"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["temp"] = temp;
    data["feels_like"] = feelsLike;
    data["temp_min"] = tempMin;
    data["temp_max"] = tempMax;
    data["pressure"] = pressure;
    data["sea_level"] = seaLevel;
    data["grnd_level"] = grndLevel;
    data["humidity"] = humidity;
    data["temp_kf"] = tempKf;
    return data;
  }
}

class WeatherCallDaysList {
/*
{
  "dt": 1627905600,
  "main": {
    "temp": 18.55,
    "feels_like": 17.9,
    "temp_min": 18.55,
    "temp_max": 20.84,
    "pressure": 1016,
    "sea_level": 1016,
    "grnd_level": 1012,
    "humidity": 55,
    "temp_kf": -2.29
  },
  "weather": [
    {
      "id": 801,
      "main": "Clouds",
      "description": "few clouds",
      "icon": "02d"
    }
  ],
  "clouds": {
    "all": 14
  },
  "wind": {
    "speed": 1.37,
    "deg": 59,
    "gust": 1.64
  },
  "visibility": 10000,
  "pop": 0,
  "sys": {
    "pod": "d"
  },
  "dt_txt": "2021-08-02 12:00:00"
} 
*/

  int? dt;
  WeatherCallDaysListMain? main;
  List<WeatherCallDaysListWeather?>? weather;
  WeatherCallDaysListClouds? clouds;
  WeatherCallDaysListWind? wind;
  int? visibility;
  int? pop;
  WeatherCallDaysListSys? sys;
  String? dtTxt;

  WeatherCallDaysList({
    this.dt,
    this.main,
    this.weather,
    this.clouds,
    this.wind,
    this.visibility,
    this.pop,
    this.sys,
    this.dtTxt,
  });
  WeatherCallDaysList.fromJson(Map<String, dynamic> json) {
    dt = json["dt"]?.toInt();
    main = (json["main"] != null)
        ? WeatherCallDaysListMain.fromJson(json["main"])
        : null;
    if (json["weather"] != null) {
      final v = json["weather"];
      final arr0 = <WeatherCallDaysListWeather>[];
      v.forEach((v) {
        arr0.add(WeatherCallDaysListWeather.fromJson(v));
      });
      weather = arr0;
    }
    clouds = (json["clouds"] != null)
        ? WeatherCallDaysListClouds.fromJson(json["clouds"])
        : null;
    wind = (json["wind"] != null)
        ? WeatherCallDaysListWind.fromJson(json["wind"])
        : null;
    visibility = json["visibility"]?.toInt();
    pop = json["pop"]?.toInt();
    sys = (json["sys"] != null)
        ? WeatherCallDaysListSys.fromJson(json["sys"])
        : null;
    dtTxt = json["dt_txt"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dt"] = dt;
    if (main != null) {
      data["main"] = main!.toJson();
    }
    if (weather != null) {
      final v = weather;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["weather"] = arr0;
    }
    if (clouds != null) {
      data["clouds"] = clouds!.toJson();
    }
    if (wind != null) {
      data["wind"] = wind!.toJson();
    }
    data["visibility"] = visibility;
    data["pop"] = pop;
    if (sys != null) {
      data["sys"] = sys!.toJson();
    }
    data["dt_txt"] = dtTxt;
    return data;
  }
}

class WeatherCallDays {
/*
{
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1627905600,
      "main": {
        "temp": 18.55,
        "feels_like": 17.9,
        "temp_min": 18.55,
        "temp_max": 20.84,
        "pressure": 1016,
        "sea_level": 1016,
        "grnd_level": 1012,
        "humidity": 55,
        "temp_kf": -2.29
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "clouds": {
        "all": 14
      },
      "wind": {
        "speed": 1.37,
        "deg": 59,
        "gust": 1.64
      },
      "visibility": 10000,
      "pop": 0,
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2021-08-02 12:00:00"
    }
  ],
  "city": {
    "id": 2643743,
    "name": "London",
    "coord": {
      "lat": 51.5085,
      "lon": -0.1257
    },
    "country": "GB",
    "population": 1000000,
    "timezone": 3600,
    "sunrise": 1627878351,
    "sunset": 1627933654
  }
} 
*/

  String? cod;
  int? message;
  int? cnt;
  List<WeatherCallDaysList?>? list;
  WeatherCallDaysCity? city;

  WeatherCallDays({
    this.cod,
    this.message,
    this.cnt,
    this.list,
    this.city,
  });
  WeatherCallDays.fromJson(Map<String, dynamic> json) {
    cod = json["cod"]?.toString();
    message = json["message"]?.toInt();
    cnt = json["cnt"]?.toInt();
    if (json["list"] != null) {
      final v = json["list"];
      final arr0 = <WeatherCallDaysList>[];
      v.forEach((v) {
        arr0.add(WeatherCallDaysList.fromJson(v));
      });
      list = arr0;
    }
    city = (json["city"] != null)
        ? WeatherCallDaysCity.fromJson(json["city"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["cod"] = cod;
    data["message"] = message;
    data["cnt"] = cnt;
    if (list != null) {
      final v = list;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["list"] = arr0;
    }
    if (city != null) {
      data["city"] = city!.toJson();
    }
    return data;
  }
}
